# If we can, use uv (https://docs.astral.sh/uv/) to manage a virtual environment and run commands.
# Otherwise, require an active virtual environment and directly run commands.
uv := $(shell command -v uv 2>/dev/null)
prerun :=
runner :=
ifneq ($(strip $(uv)),)
runner := uv run
else ifndef VIRTUAL_ENV
prerun = $(error You have not activated a virtual environment)
endif

.DEFAULT_GOAL := help

.PHONY: run format lint clean help

run:
	$(prerun)
	$(runner) pytest -vv

format:
	$(prerun)
	$(runner) ruff format

lint:
	$(prerun)
	$(runner) ruff check
	$(runner) ruff format --diff
	$(runner) pyright

clean:
	@rm -rf *.egg-info .venv __pycache__ .pytest_cache .ruff_cache

help:
	@echo "Test the Vale rules                     make run"
	@echo "Format the testing code                 make format"
	@echo "Check the quality of the testing code   make lint"
